packages:
  - "apps/**"
  - "packages/*"
  - "!packages/service-template"

allowBuilds:
  "prisma": true
  "@prisma/client": true
  "@prisma/engines": true
  "esbuild": true
  "cpu-features": true
  "protobufjs": true
  "ssh2": true
